name: Upload to CurseForge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Zip Archive
        run: zip -r ClassicPlusPro.zip * -x "*.git*" -x "*.github*"

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@3.1.1
        with:
          file_path: "./ClassicPlusPro.zip"
          display_name: "Classic+ Pro Beta 0.1"
          game_endpoint: "wow"
          project_id: 941941
          token: ${{ secrets.CURSEFORGE }}
          game_versions: "1.15.0"
          release_type: "beta"  # Can be 'alpha', 'beta', or 'release'