name: Upload to CurseForge

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Zip the project
      run: zip -r Classi-Plus-Pro.zip .

    - name: Upload to CurseForge
      env:
        CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        PROJECT_ID: [941941]
      run: |
        curl -X POST \
             -H "X-Api-Token: $CURSEFORGE_API_KEY" \
             -F "file=@my_project.zip" \
             -F "metadata={\"changelog\": \"New update\", \"changelogType\": \"text\", \"gameVersions\": [\"1.0\"], \"releaseType\": \"release\"}" \
             "https://minecraft.curseforge.com/api/projects/$PROJECT_ID/upload-file"
